### ISSUE TITLE
AE 致密线缆纹理错误

### ISSUE THREAD

**Issue by ZHAY10086** [RuiXuqi/ModernityExtra#7]
如图所示
![图片](https://github.com/RuiXuqi/ModernityExtra/assets/34602681/34f41232-a0e6-40f3-9ec8-155b3f9bec51)

**Comment by RuiXuqi** [comment]
已知，待修复

**Comment by RuiXuqi** [comment]
并未修复，只是因为ae2uel改了渲染方式所以方块没问题了，预计会回滚那次提交以保证ae2原版兼容性
