### ISSUE TITLE
AE2 Stuff 高级压印器纹理错误

### ISSUE THREAD

**Issue by ZHAY10086** [RuiXuqi/ModernityExtra#9]
![9d1f47bda33432ccadc4ca1b141ac0cd](https://github.com/RuiXuqi/ModernityExtra/assets/34602681/da9a0629-0541-4a4d-a1a3-7eb476657911)
如图所示，机器工作时为资源包内纹理，不工作时仍为原版纹理

**Comment by RuiXuqi** [comment]
看样子是blockstates写错了（）
最近不摸电脑，有空来修（）

**Comment by RuiXuqi** [comment]
OK搞完了，顺带改了下催生仓的状态，把高级压印器粒子的问题也修了
